/**
 * IDs dos Casos de Teste (TC)
 * Formato: TC-[AREA]-[TIPO]-[NUMERO]
 * Exemplo: TC-FRONTEND-FUNC-0001
 */

export const TEST_IDS = {
  // Testes Funcionais Frontend
  FRONTEND: {
    FUNC: {
      PESQUISA_CEP_VALIDO: 'TC-FRONTEND-FUNC-0001',
      PESQUISA_CEP_INVALIDO: 'TC-FRONTEND-FUNC-0002',
      PESQUISA_CEP_NAO_EXISTENTE: 'TC-FRONTEND-FUNC-0003'
    },
    REGR: {
      PESQUISA_CEP_VALIDO: 'TC-FRONTEND-REGR-0001',
      PESQUISA_CEP_INVALIDO: 'TC-FRONTEND-REGR-0002',
      PESQUISA_CEP_FORMATO_INVALIDO: 'TC-FRONTEND-REGR-0003'
    }
  },

  // Testes Funcionais API
  API: {
    FUNC: {
      BUSCA_CEP_VALIDO: 'TC-API-FUNC-0001',
      BUSCA_CEP_INVALIDO: 'TC-API-FUNC-0002',
      BUSCA_CEP_NAO_EXISTENTE: 'TC-API-FUNC-0003'
    },
    REGR: {
      BUSCA_CEP_VALIDO: 'TC-API-REGR-0001',
      BUSCA_CEP_INVALIDO: 'TC-API-REGR-0002',
      BUSCA_CEP_FORMATO_INVALIDO: 'TC-API-REGR-0003'
    }
  }
}; 